// src/utils/skillClusterMap.ts

export const SKILL_CLUSTERS: Record<string, string[]> = {
    Frontend: [
        "react",
        "next",
        "vue",
        "angular",
        "html",
        "css",
        "sass",
        "tailwind",
        "bootstrap",
        "javascript",
        "typescript",
    ],

    Backend: [
        "node",
        "express",
        "nestjs",
        "django",
        "flask",
        "spring",
        "postgres",
        "mongodb",
        "mysql",
        "redis",
        "graphql",
        "rest api",
    ],

    DevOps: [
        "docker",
        "kubernetes",
        "aws",
        "azure",
        "gcp",
        "terraform",
        "ansible",
        "ci/cd",
        "jenkins",
        "github actions",
        "nginx",
    ],

    AI_ML: [
        "machine learning",
        "deep learning",
        "tensorflow",
        "pytorch",
        "keras",
        "nlp",
        "computer vision",
        "llm",
        "transformers",
        "neural networks",
    ],

    Data: [
        "data analysis",
        "data science",
        "pandas",
        "numpy",
        "sql",
        "power bi",
        "tableau",
        "spark",
        "hadoop",
        "big data",
    ],

    Mobile: [
        "android",
        "ios",
        "flutter",
        "react native",
        "swift",
        "kotlin",
    ],

    CyberSecurity: [
        "cyber security",
        "penetration testing",
        "ethical hacking",
        "metasploit",
        "burp suite",
        "wireshark",
        "network security",
        "cryptography",
        "owasp",
        "vulnerability assessment",
        "siem",
        "soc",
    ],

    Systems_Programming: [
        "c programming",
        "c language",
        "c++",
        "rust",
        "go programming",
        "golang",
        "assembly",
        "operating systems",
        "linux kernel",
        "embedded systems",
        "multithreading",
        "low level programming",
    ],

    Blockchain: [
        "blockchain",
        "solidity",
        "web3",
        "smart contracts",
        "ethereum",
        "hyperledger",
    ],

    Cloud_Architecture: [
        "cloud architecture",
        "microservices",
        "distributed systems",
        "serverless",
        "event driven architecture",
    ],

    Product_Engineering: [
        "product management",
        "roadmap planning",
        "user research",
        "a/b testing",
    ],

    Prompt_Engineering: [
        "prompt engineering",
        "llm applications",
        "rag",
        "retrieval augmented generation",
        "langchain",
        "vector database",
        "openai api",
        "gemini api",
        "fine tuning",
    ],

    Other: [],
};